[build]
  base = "secret-santa"
  command = "npm run build"
  publish = "dist/secret-santa/browser"
  functions = "../netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
