[build]
  base = "secret-santa"
  command = "npm run build"
  publish = "dist/secret-santa/browser"

[functions]
  directory = "../netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
