[build]
  base = "secret-santa"
  command = "npm run build && cd ../netlify/functions && npm ci"
  publish = "dist/secret-santa/browser"
  functions = "../netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
