[build]
  base = "secret-santa"
  command = "npm run build"
  publish = "dist/secret-santa"

[functions]
  directory = "../netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
