[build]
  base = "secret-santa"
  command = "npm run build"
  publish = "dist/secret-santa/browser"
  functions = "../netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
